apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: keycloak-chaos
  namespace: keycloak-argocd-app
spec:
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'keycloak-argocd-app'
    applabel: 'app=keycloak'
    appkind: 'statefulset'
  chaosServiceAccount: container-kill-sa
  monitoring: false
  # It can be delete/retain
  jobCleanUpPolicy: 'retain' 
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            # specify the name of the container to be killed
            - name: TARGET_CONTAINER
              value: 'keycloak-argocd-app'
            # provide the chaos interval
            - name: CHAOS_INTERVAL
              value: '10'
            # provide the total chaos duration
            - name: TOTAL_CHAOS_DURATION
              value: '20'