---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-kill-sa
  labels:
    name: container-kill-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: container-kill-sa
  labels:
    name: container-kill-sa
rules:
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update","delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","list","get","patch","update","delete"]
- apiGroups: [""]
  resources: ["pods","pods/exec"]
  verbs: ["create","list","get","patch","update","delete"]
- apiGroups: [""]
  resources: ["pods/log","events"]
  verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: container-kill-sa
  labels:
    name: container-kill-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: container-kill-sa
subjects:
- kind: ServiceAccount
  name: container-kill-sa
  namespace: chaos-keycloak
